name: Synthetic Test
run-name: Synthetic Test
on:
  push:
    branches:
      - "**"
      - "!main"
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Test
        run: yarn ci:install && yarn ci:test
