name: Synthetic Test
run-name: Synthetic Test
on:
  push:
    - "**"
    - "!main"
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Test
        run: yarn ci:install && yarn ci:test
